#!/bin/bash

screen -ls | awk -vFS='\t|[.]' '/backend-service-screen/ {system("screen -S "$2" -X quit")}'
screen -d -m -S backend-service-screen bash -c 'python3 /etc/project-kastje/backend-service/service.py'
sudo screen -list 2>&1 | tee installer.log
